### ISSUE TITLE
Packaging improvements for v1.0.0

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#209]
This issue is just a collection of small tasks that can improve packaging (in a broad sense) for v1.0.0. The general goal is to simplify the project (fewer/simpler files relating to integrations) and use standard tools (already using TravisCI and ReadTheDocs... Maybe use codecov.io?).

- [x] Pin several versions of documentation at ReadTheDocs: v0.9.2, v1.0.0
- [x] Remove tox requirement
  - [x] Better document virtual environment usage
  - [x] Update `.travis.tml`
  - [x] Remove `tox.ini`
- [x] [Fix PyPI readme](https://packaging.python.org/guides/making-a-pypi-friendly-readme/)
- [x] Update badges
  - [x] Only have 'develop' for TravisCI
  - [x] Add Python version, PyPI package version (https://shields.io/)
  - [x] ~~Add code coverage ([codecov.io](https://codecov.io/) or [coverage-badge](https://pypi.org/project/coverage-badge/))~~ Pass on this for now; the `CONTRIBUTING.md` file explains how to get test coverage
- [x] Disable the defunct wiki
- [x] ~~Git annotated tags (see #158)~~ Also pass for now; there's no obvious need at this time
- [x] Make `delphin` and `delphin.codecs` namespace packages (see #222; but distribute all together for now)
- [x] ~~Release v1.0.0 as `delphin` on PyPI (see #182)~~ Until there's a reason to separate a `delphin` base package from PyDelphin, there seems to be little need to upload to the `delphin` project on PyPI.
